# Generated by Django 4.2.7 on 2025-09-23 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0002_paymentrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("chat_tokens", models.PositiveIntegerField(default=0)),
                ("admin_tokens", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "token_usage",
                "ordering": ["-date", "user"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="token_usage_user_id_50d383_idx"
                    ),
                    models.Index(fields=["date"], name="token_usage_date_0fa976_idx"),
                    models.Index(
                        fields=["user", "-date"], name="token_usage_user_id_57fa0a_idx"
                    ),
                ],
                "unique_together": {("user", "date")},
            },
        ),
    ]
