# Generated by Django 4.2.7 on 2025-09-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_clientinfo_monthly_revenue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(
                blank=True,
                help_text="Token for password reset via magic link",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_created",
            field=models.DateTimeField(
                blank=True,
                help_text="When the password reset token was created",
                null=True,
            ),
        ),
    ]
