# Generated by Django 4.2.7 on 2025-09-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_user_password_reset_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_attempts_today",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of password reset attempts made today"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_last_attempt_date",
            field=models.DateField(
                blank=True, help_text="Date of last password reset attempt", null=True
            ),
        ),
    ]
